---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dq-business-data-manager
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: dq-business-data-manager
    spec:
      containers:
      - name: dq-business-data-manager
        image: quay.io/ukhomeofficedigital/business-data-manager:{{.DRONE_COMMIT_SHA}}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: NODE_ENV
            value: {{ .NODE_ENV }}
          - name: LOG_LEVEL
            value: {{ .LOG_LEVEL }}
          - name: NAME
            value: 'business-data-manager'
          - name: PORT
            value: '8080'
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                name: bdm
                key: sessionsecret
          - name: TITLE
            value: 'Business Data Manager'
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: {{ .RDS_SECRET_NAME }}
                key: endpoint
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: {{ .RDS_SECRET_NAME }}
                key: port
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: {{ .RDS_SECRET_NAME }}
                key: username
          - name: PGDATABASE
            valueFrom:
              secretKeyRef:
                name: {{ .RDS_SECRET_NAME }}
                key: {{ .DB_ATTRIBUTE }}
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .RDS_SECRET_NAME }}
                key: password
      - name: keycloak-proxy
        image: quay.io/ukhomeofficedigital/go-keycloak-proxy:v2.3.0
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: PROXY_ENABLE_CORS_GLOBAL
            value: 'true'
          - name: PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: dq-business-data-manager
                key: KEYCLOAK_CLIENT_ID
          - name: PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: dq-business-data-manager
                key: KEYCLOAK_CLIENT_SECRET
          - name: PROXY_DISCOVERY_URL
            valueFrom:
              secretKeyRef:
                name: dq-business-data-manager
                key: KEYCLOAK_DISCOVERY
        args:
          - --enable-logging
          - --enable-json-logging
          - --listen=0.0.0.0:8081
          - --upstream-url=http://127.0.0.1:8080
          - --upstream-keepalives
          - --cors-origins=*
          - --enable-login-handler
          - --secure-cookie=true
          - --http-only-cookie=true
          - --verbose
          - --upstream-timeout=60s
          - --upstream-keepalive-timeout=60s
          - --upstream-tls-handshake-timeout=60s
          - --upstream-response-header-timeout=60s
          - --upstream-expect-continue-timeout=60s
          - --server-read-timeout=60s
          - --server-write-timeout=60s
          - --enable-default-deny=true
          - --resources=uri=/*|roles=bdm
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8081'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443
